package com.reeman.agv.constants

enum class SettingPage {
    PAGE_BASIC_SETTING,
    PAGE_LANGUAGE_SETTING,
    PAGE_NETWORK_SETTING,
    PAGE_MODE_SETTING,
    PAGE_RETURNING_SETTING,
    PAGE_ELEVATOR_SETTING,
    PAGE_DOOR_SETTING,
    PAGE_DISPATCH_SETTING,
    PAGE_VERSION_SETTING,
}